### ISSUE TITLE
Require Images for ARM64

### ISSUE THREAD

**Issue by odidev** [SumoLogic/sumologic-kubernetes-fluentd#180]
I am trying to use kubernetes-fluentd image over ARM64v8 but it seems it does not have an arm64 supported tag in the [docker hub](https://hub.docker.com/r/sumologic/kubernetes-fluentd)

I have successfully built the [image ](https://hub.docker.com/layers/odidev/kubernetes-fluentd/latest-arm64/images/sha256-964035d62bca88841ed662e4e454ee79b52afb23e69947492f2a696143906002?context=explore) on ARM64 platform by implementing these [changes.](https://github.com/odidev/sumologic-kubernetes-fluentd/commit/59b9b8d819cd46a5d2bb3e900159400d15a6883b)

**ARM64 Image:** https://hub.docker.com/layers/odidev/kubernetes-fluentd/latest-arm64/images/sha256-964035d62bca88841ed662e4e454ee79b52afb23e69947492f2a696143906002?context=explore

**Changes :** https://github.com/odidev/sumologic-kubernetes-fluentd/commit/59b9b8d819cd46a5d2bb3e900159400d15a6883b

Do you have any plans for releasing an ARM64 image?

If interested, I will raise a PR.

**Comment by perk-sumo** [comment]
Hi @odidev - this is awesome! Can you confirm it's working for you as expected?

Answering your question: yes, we keep an eye on that for some time now and we have plans on releasing the ARM64 Fluentd image.

**Comment by odidev** [comment]
Yes, this [image ](https://hub.docker.com/layers/odidev/kubernetes-fluentd/latest-arm64/images/sha256-964035d62bca88841ed662e4e454ee79b52afb23e69947492f2a696143906002?context=explore) is working fine for me.  Please check and let me know if any updates are required in the changes mentioned. If agreed, I will raise the PR with my changes.

**Comment by astencel-sumo** [comment]
Hey @odidev, thanks a lot for raising this issue. I've been working on a solution based on the same idea as yours - replacing the Fluentd base image tag is the only change needed in Dockerfile.

I've created a PR myself - #187, hope it's OK. Please take a look and let me know if it works for you.

**Comment by astencel-sumo** [comment]
This is now fixed with #187 being merged and https://github.com/SumoLogic/sumologic-kubernetes-fluentd/releases/tag/v1.12.2-sumo-1 released 🎉
