### ISSUE TITLE
Supplied sumologic installer doesn't provide high enough version of fluentd to avoid vulnerability

### ISSUE THREAD

**Issue by jyu-tera** [SumoLogic/sumologic-kubernetes-fluentd#295]
Using sumo collector tools version 2.4.1 provides fluentd image version 1.12.2-sumo-0.

This version of fluentd has multiple high security vulnerabilities due to rdoc:6.1.2, rexml:3.1.9, addressable:2.7.0, bundler:1.7.2, and webrick:1.4.2 as seen in a below screenshot from our Sysdig scan. VULNDB results are 3rd party and are not part of a public feed.
![image](https://user-images.githubusercontent.com/84815526/125693481-b88a720f-5631-4cc6-b1a4-9c552cc52121.png)

Can the installer version used be bumped up to resolve this?

**Comment by astencel-sumo** [comment]
Yes we definitely need to release a newer version of the image. Will release `v1.12.2-sumo-2` as soon as possible.

**Comment by astencel-sumo** [comment]
Release [v1.12.2-sumo-2](https://github.com/SumoLogic/sumologic-kubernetes-fluentd/releases/tag/v1.12.2-sumo-2) is now published.

I'm afraid this will not resolve all the vulnerabilities reported by your scanner. However, I believe the reported vulnerabilities are either false positives (like `webrick`, which I don't think exists in our image) or harmless (like `bundler`).

Removing all of the vulnerabilities would require significant changes in how we operate Fluentd, which is not what we want to focus on at the moment. We are concentrating our efforts on replacing Fluentd with OpenTelemetry Collector.

Hope this is a helpful explanation. I'll close this issue now, but please comment on it or create a new issue if you have further remarks.
